### ISSUE TITLE
Issue while grabbing the login url :/

### ISSUE THREAD

**Issue by praeludiumOrbis** [WhosMyName/ProxLoadMe#6] opened 2020-08-20 20:49 UTC
E:\Program Files\ProxLoadMe>python ProxLoadMe.py
2020-08-20 22:48:50,668 | ERROR | ProxLoadMe plme.main 11656 11540 |           init_preps() - Line 82 | 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "ProxLoadMe.py", line 78, in init_preps
    url = soup.find("form")["action"] # grab the login url
TypeError: 'NoneType' object is not subscriptable
2020-08-20 22:48:50,670 | WARNING | ProxLoadMe plme.main 11656 11540 |           init_preps() - Line 83 | Something went wrong during Login!
Exiting...

E:\Program Files\ProxLoadMe>

**Comment by WhosMyName** [comment] 2020-08-24 07:49
As you might have seen, Proxer is now using Cloudflare, this Issues will be probably caused by this change.
I'll check it out the comming days. UwU

**Comment by WhosMyName** [comment] 2020-08-31 23:56
Issue is fixed in 50e5da2.
<3

**Closed as completed by WhosMyName** 2020-08-31 23:56 UTC
Labels: bug
